version: "3.8"
services:
  calc_server:
    container_name: calc_server
    build: ./server
    env_file:
      - ./server/.env
    ports:
      - 8080:8080
    volumes:
      - ./server/src:/server/src

  calc_app:
    container_name: calc_app
    build: ./app
    env_file:
      - ./app/.env
    environment:
      - CI=true
    ports:
      - 3000:3000
    volumes:
      - ./app/src:/app/src
      - ./app/public:/app/public
      - /app/node_modules
    links:
      - calc_server
    depends_on:
      - calc_server
